### PR TITLE
Update check_mysql_audit_log_status.sh

### PR DESCRIPTION
**Pull request by arch3x**
notification will only be sent once.

### CODE REVIEW

**Comment by guriandoro** [comment]
Hey Arch3x!

Thanks for the PR, and sorry for the delay in reply.

I can definitely merge this, but there seems to be some email accounts specific to cpg :) Do you want to edit them out, or should I merge and edit myself?

Have you tried the code? I can do it, but it will take some time to set up the environment, so if you can confirm it's working it would be great.

Agustín.

**Comment by arch3x** [comment]
Hi Agustin,

I've tested the script and it works great. I've modify to include slack
notification and to try to auto-resolve errors like not writing to audit
file. See attachment.

Thanks,
Henry

**Comment by guriandoro** [comment]
Awesome! Thanks, Henry.

I didn't get the attachments, though, maybe because you replied directly via email?

I have merged this, feel free to create a new one for the additional functionality you mentioned.


Agustín.

**Comment by arch3x** [comment]
Hi Agustin,

I've requested another pull request.

Thanks,
Henry

**Pull request merged**
